version: "3"

services:
  ### Nginx container #########################################
  nginx:
    container_name: dnmp-nginx
    image: nginx:latest
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ${WWW_DIR}:/etc/nginx/html/:rw
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/vhost:/etc/nginx/conf.d:ro
      - ./config/nginx/rewrite:/etc/nginx/rewrite:ro
      - ./log/nginx:/var/log/nginx:rw
    restart: always
    privileged: true
    networks:
      - default

  ### PHP container #########################################
  php56:
    container_name: dnmp-php56
    build:
      context: ./build/php56
      args:
        TIME_ZONE: ${GLOBAL_TIME_ZONE}
        CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
    ports:
      - "${PHP56_FPM_PORT}:9000"
    volumes:
      - ${WWW_DIR}:/etc/nginx/html:rw
      - ./config/php56/php.ini:/usr/local/etc/php/php.ini:ro
      - ./config/php56/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php56:/var/log:rw
    restart: always
    privileged: true
    environment:
      TZ: "$GLOBAL_TIME_ZONE"
    networks:
      - default

  php74:
    container_name: dnmp-php74
    build:
      context: ./build/php74
      args:
        TIME_ZONE: ${GLOBAL_TIME_ZONE}
        CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
    ports:
      - "${PHP74_FPM_PORT}:9000"
    volumes:
      - ${WWW_DIR}:/etc/nginx/html:rw
      - ./config/php74/php.ini:/usr/local/etc/php/php.ini:ro
      - ./config/php74/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php74:/var/log:rw
    restart: always
    privileged: true
    environment:
      TZ: "$GLOBAL_TIME_ZONE"
    networks:
      - default

  php8:
    container_name: dnmp-php8
    build:
      context: ./build/php8
      args:
        TIME_ZONE: ${GLOBAL_TIME_ZONE}
        CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
    ports:
      - "${PHP8_FPM_PORT}:9000"
    volumes:
      - ${WWW_DIR}:/etc/nginx/html:rw
      - ./config/php8/php.ini:/usr/local/etc/php/php.ini:ro
      - ./config/php8/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php8:/var/log:rw
    restart: always
    privileged: true
    environment:
      TZ: "$GLOBAL_TIME_ZONE"
    networks:
      - default

  ### Mysql container #########################################
  mysql:
    container_name: dnmp-mysql
    image: mysql:5.7
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./log/mysql:/var/log/mysql:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "$GLOBAL_TIME_ZONE"
    networks:
      - default

  ### Redis container #########################################
  redis:
    container_name: dnmp-redis
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./log/redis:/var/log/redis:rw
      - ./data/redis:/data:rw
    restart: always
    privileged: true
    networks:
      - default

  ### Elasticsearch container #########################################
  # es:
  #   container_name: dnmp-es
  #   build:
  #     context: ./build/elasticsearch
  #     args:
  #       ELASTICSEARCH_VERSION: ${ELASTICSEARCH_VERSION}
  #       ELASTICSEARCH_PLUGINS: ${ELASTICSEARCH_PLUGINS}
  #   environment:
  #     - TZ=$GLOBAL_TIME_ZONE
  #     - discovery.type=single-node
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   volumes:
  #     - ./data/elasticsearch:/usr/share/elasticsearch/data
  #     - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  #   hostname: es
  #   restart: always
  #   ports:
  #    - "${ELASTICSEARCH_HOST_PORT_C}:9200"
  #    - "${ELASTICSEARCH_HOST_PORT_S}:9300"
  #   networks:
  #     - default
  
  ### Supervisor container ####################################
  # supervisor:
  #   container_name: dnmp-supervisor
  #   build:
  #     context: ./services/supervisor
  #     args:
  #       ALPINE_VERSION: alpine:${ALPINE_VERSION}
  #       TZ: "$GLOBAL_TIME_ZONE"
  #   ports:
  #     - "${SUPERVISOR_HOST_PORT_C}:9001"
  #   volumes:
  #     - ./log/supervisor:/var/log/supervisor/:rw
  #     - ./config/supervisor/conf.d:/etc/supervisor/conf.d/:rw
  #     - ./config/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf:ro
  #   command:
  #     - /bin/sh
  #     - -c
  #     - |
  #       supervisord -n -c /etc/supervisor/supervisord.conf
  #   restart: always
  #   cap_add:
  #     - SYS_PTRACE
  #   networks:
  #     - default

networks:
  default: